-- =============================================
-- Application: Sample 01 - Basic SaveToDB Features
-- Version 10.8, January 9, 2023
--
-- Copyright 2014-2023 Gartle LLC
--
-- License: MIT
-- =============================================

CREATE USER SAMPLE01_USER1 PASSWORD 'Usr_2011#_Xls4168';
CREATE USER SAMPLE01_USER2 PASSWORD 'Usr_2011#_Xls4168';

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE S01.CASHBOOK      TO SAMPLE01_USER1, SAMPLE01_USER2;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE S01.FORMATS       TO SAMPLE01_USER1, SAMPLE01_USER2;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE S01.WORKBOOKS     TO SAMPLE01_USER1, SAMPLE01_USER2;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE S01.VIEW_CASHBOOK TO SAMPLE01_USER1, SAMPLE01_USER2;

GRANT SELECT ON ALL SEQUENCES IN SCHEMA S01                     TO SAMPLE01_USER1, SAMPLE01_USER2;

GRANT EXECUTE ON PROCEDURE S01.USP_CASHBOOK                     TO USER SAMPLE01_USER1, SAMPLE01_USER2;
GRANT EXECUTE ON PROCEDURE S01.USP_CASHBOOK2                    TO USER SAMPLE01_USER1, SAMPLE01_USER2;
GRANT EXECUTE ON PROCEDURE S01.USP_CASHBOOK3                    TO USER SAMPLE01_USER1, SAMPLE01_USER2;
GRANT EXECUTE ON PROCEDURE S01.USP_CASHBOOK4                    TO USER SAMPLE01_USER1, SAMPLE01_USER2;
GRANT EXECUTE ON PROCEDURE S01.USP_CASHBOOK2_INSERT             TO USER SAMPLE01_USER1, SAMPLE01_USER2;
GRANT EXECUTE ON PROCEDURE S01.USP_CASHBOOK2_UPDATE             TO USER SAMPLE01_USER1, SAMPLE01_USER2;
GRANT EXECUTE ON PROCEDURE S01.USP_CASHBOOK2_DELETE             TO USER SAMPLE01_USER1, SAMPLE01_USER2;
GRANT EXECUTE ON PROCEDURE S01.USP_CASHBOOK3_CHANGE             TO USER SAMPLE01_USER1, SAMPLE01_USER2;
GRANT EXECUTE ON PROCEDURE S01.USP_CASHBOOK4_MERGE              TO USER SAMPLE01_USER1, SAMPLE01_USER2;
GRANT EXECUTE ON PROCEDURE S01.USP_CASH_BY_MONTHS               TO USER SAMPLE01_USER1, SAMPLE01_USER2;
GRANT EXECUTE ON PROCEDURE S01.USP_CASH_BY_MONTHS_CHANGE        TO USER SAMPLE01_USER1, SAMPLE01_USER2;
