-- =============================================
-- Application: Sample 01 - Basic SaveToDB Features
-- Version 10.13, April 29, 2024
--
-- Copyright 2014-2024 Gartle LLC
--
-- License: MIT
-- =============================================

DROP USER SAMPLE01_USER1 IF EXISTS;
DROP USER SAMPLE01_USER2 IF EXISTS;

DROP PROCEDURE  IF EXISTS S01.USP_CASH_BY_MONTHS;
DROP PROCEDURE  IF EXISTS S01.USP_CASH_BY_MONTHS_CHANGE;
DROP PROCEDURE  IF EXISTS S01.USP_CASHBOOK;
DROP PROCEDURE  IF EXISTS S01.USP_CASHBOOK2;
DROP PROCEDURE  IF EXISTS S01.USP_CASHBOOK3;
DROP PROCEDURE  IF EXISTS S01.USP_CASHBOOK4;
DROP PROCEDURE  IF EXISTS S01.USP_CASHBOOK2_INSERT;
DROP PROCEDURE  IF EXISTS S01.USP_CASHBOOK2_UPDATE;
DROP PROCEDURE  IF EXISTS S01.USP_CASHBOOK2_DELETE;
DROP PROCEDURE  IF EXISTS S01.USP_CASHBOOK3_CHANGE;
DROP PROCEDURE  IF EXISTS S01.USP_CASHBOOK4_MERGE;

DROP VIEW       IF EXISTS S01.VIEW_CASHBOOK;

DROP TABLE      IF EXISTS S01.CASHBOOK;
DROP TABLE      IF EXISTS S01.FORMATS;
DROP TABLE      IF EXISTS S01.WORKBOOKS;

DROP SCHEMA     IF EXISTS S01;

-- print Application removed
