-- =============================================
-- Application: Sample 02 - Advanced Features
-- Version 10.8, January 9, 2023
--
-- Copyright 2017-2023 Gartle LLC
--
-- License: MIT
-- =============================================

CREATE USER SAMPLE02_USER1  PASSWORD 'Usr_2011#_Xls4168';
CREATE USER SAMPLE02_USER2  PASSWORD 'Usr_2011#_Xls4168';
CREATE USER SAMPLE02_USER3  PASSWORD 'Usr_2011#_Xls4168';

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA S02 TO SAMPLE02_USER1, SAMPLE02_USER2, SAMPLE02_USER3;

GRANT EXECUTE ON PROCEDURE S02.USP_CASHBOOK                     TO SAMPLE02_USER1, SAMPLE02_USER2, SAMPLE02_USER3;
GRANT EXECUTE ON PROCEDURE S02.USP_CASHBOOK2                    TO SAMPLE02_USER1, SAMPLE02_USER2, SAMPLE02_USER3;
GRANT EXECUTE ON PROCEDURE S02.USP_CASHBOOK3                    TO SAMPLE02_USER1, SAMPLE02_USER2, SAMPLE02_USER3;
GRANT EXECUTE ON PROCEDURE S02.USP_CASHBOOK4                    TO SAMPLE02_USER1, SAMPLE02_USER2, SAMPLE02_USER3;
GRANT EXECUTE ON PROCEDURE S02.USP_CASHBOOK5                    TO SAMPLE02_USER1, SAMPLE02_USER2, SAMPLE02_USER3;

GRANT EXECUTE ON PROCEDURE S02.USP_CASHBOOK2_INSERT             TO SAMPLE02_USER1, SAMPLE02_USER2, SAMPLE02_USER3;
GRANT EXECUTE ON PROCEDURE S02.USP_CASHBOOK2_UPDATE             TO SAMPLE02_USER1, SAMPLE02_USER2, SAMPLE02_USER3;
GRANT EXECUTE ON PROCEDURE S02.USP_CASHBOOK2_DELETE             TO SAMPLE02_USER1, SAMPLE02_USER2, SAMPLE02_USER3;
GRANT EXECUTE ON PROCEDURE S02.USP_CASHBOOK3_CHANGE             TO SAMPLE02_USER1, SAMPLE02_USER2, SAMPLE02_USER3;
GRANT EXECUTE ON PROCEDURE S02.USP_CASHBOOK4_MERGE              TO SAMPLE02_USER1, SAMPLE02_USER2, SAMPLE02_USER3;

GRANT EXECUTE ON PROCEDURE S02.USP_CASH_BY_MONTHS               TO SAMPLE02_USER1, SAMPLE02_USER2, SAMPLE02_USER3;
GRANT EXECUTE ON PROCEDURE S02.USP_CASH_BY_MONTHS_CHANGE        TO SAMPLE02_USER1, SAMPLE02_USER2, SAMPLE02_USER3;

GRANT EXECUTE ON PROCEDURE S02.XL_CONTEXT_MENU_CASH_BY_MONTHS   TO SAMPLE02_USER1, SAMPLE02_USER2, SAMPLE02_USER3;
GRANT EXECUTE ON PROCEDURE S02.XL_LIST_ACCOUNT_ID               TO SAMPLE02_USER1, SAMPLE02_USER2, SAMPLE02_USER3;
GRANT EXECUTE ON PROCEDURE S02.XL_LIST_COMPANY_ID_FOR_ITEM_ID   TO SAMPLE02_USER1, SAMPLE02_USER2, SAMPLE02_USER3;
GRANT EXECUTE ON PROCEDURE S02.XL_LIST_COMPANY_ID_WITH_ITEM_ID  TO SAMPLE02_USER1, SAMPLE02_USER2, SAMPLE02_USER3;
GRANT EXECUTE ON PROCEDURE S02.XL_LIST_ITEM_ID                  TO SAMPLE02_USER1, SAMPLE02_USER2, SAMPLE02_USER3;

GRANT SELECT  ON XLS.FORMATS                                    TO SAMPLE02_USER1, SAMPLE02_USER2;
GRANT SELECT  ON XLS.WORKBOOKS                                  TO SAMPLE02_USER1, SAMPLE02_USER2;

GRANT XLS.XLS_USERS                                             TO SAMPLE02_USER3 DEFAULT;
